name: Checks
on:
  pull_request:
    branches:
      - main
jobs:
  list-workspaces:
    runs-on: ubuntu-latest
    name: list workspaces
    outputs:
      test-size: ${{ steps.set-matrix.outputs.test-size }}
      build-storybook: ${{ steps.set-matrix.outputs.build-storybook }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - id: set-matrix
        run: node .github/workflows/list-workspaces.js test:size build:storybook >> $GITHUB_OUTPUT
  size:
    runs-on: ubuntu-latest
    needs: list-workspaces
    strategy:
      matrix:
        workspace: ${{ fromJson(needs.list-workspaces.outputs.test-size) }}
    name: ${{ matrix.workspace }} / size-limit
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Check size
        uses: andresz1/size-limit-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
          directory: packages/${{ matrix.workspace }}/
  editorconfig:
    runs-on: ubuntu-latest
    name: editorconfig
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Check editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@main
  package-json:
    runs-on: ubuntu-latest
    name: package.json
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Check package.json files
        run: pnpm --package=@trigen/lint-package-json dlx lint-package-json --monorepo --ignore examples
  storybook:
    runs-on: ubuntu-latest
    needs: list-workspaces
    strategy:
      matrix:
        workspace: ${{ fromJson(needs.list-workspaces.outputs.build-storybook) }}
    name: ${{ matrix.workspace }} / storybook
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check storybook
        run: pnpm --filter ${{ matrix.workspace }} --if-present build:storybook
  website:
    runs-on: ubuntu-latest
    name: website
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check website
        run: pnpm docs:build
